parameters:
  storage_options:
    local: Slink\Shared\Infrastructure\FileSystem\Storage\LocalStorage
    smb: Slink\Shared\Infrastructure\FileSystem\Storage\SmbStorage

services:
  Slink\Shared\Infrastructure\FileSystem\Storage\StorageInterface:
    factory: ['@Slink\Shared\Infrastructure\FileSystem\StorageFactory', 'create']
    arguments:
      $storageOptions: '%storage_options%'