version: "3.8"

services:
  slink:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
