version: "3.8"

services:
  slink:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
      - node_modules:/app/client/node_modules
    ports:
      - "5173:5173"
    environment:
      - API_ENABLED=true
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  node_modules: