version: "3.8"

services:
  slink:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
      - client:/app/client
    ports:
      - "8080:8080"
    environment:
      - API_ENABLED=true
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  client: