services:
  slink:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ../apps:/apps
      - ../var:/app/var
      - ../slink:/app/slink
      - node_modules:/apps/client/node_modules
    ports:
      - "8080:8080"
      - "5173:5173"
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  node_modules: