services:
  slink:
    image: anirdev/slink:latest
    ports:
       - '3000:3000'
    container_name: slink
    restart: always
    environment:
      - TZ=Europe/Kyiv
      - SWOOLE_WORKER_NUM=4
      - API_ENABLED=true
