parameters:
  doctrine_mappings:
    User:
      dir: '%kernel.project_dir%/src/Slink/User/Infrastructure/ReadModel/View'
      prefix: 'Slink\User\Infrastructure\ReadModel\View'
    Image:
      dir: '%kernel.project_dir%/src/Slink/Image/Infrastructure/ReadModel/View'
      prefix: 'Slink\Image\Infrastructure\ReadModel\View'
    ImageEmbedded:
      dir: '%kernel.project_dir%/src/Slink/Image/Domain/ValueObject'
      prefix: 'Slink\Image\Domain\ValueObject'