name: Publish Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Extract tag name
        id: prep
        run: echo "::set-output name=tag_version::${GITHUB_REF#refs/tags/v}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/slink:${{ steps.prep.outputs.tag_version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/slink:latest
          platforms: linux/amd64,linux/arm64

      - name: Cleanup
        uses: docker/build-push-action@v3
        with:
          cleanup: true
